#!/usr/bin/env python

# build_timestamp.py — regenerates include/build_timestamp.h with the current
# wall-clock time before each build.  Only webserver.cpp includes this header,
# so the incremental build only recompiles that one file, keeping builds fast.

Import("env")
import datetime
import os

ts = datetime.datetime.now().strftime("%b %d %Y %H:%M:%S")
header_path = os.path.join(env.subst("$PROJECT_DIR"), "include", "build_timestamp.h")

with open(header_path, "w") as f:
    f.write(f'#pragma once\n// Auto-generated by tools/build_timestamp.py — do not edit\n#define BUILD_TIMESTAMP "{ts}"\n')

print(f"Build timestamp: {ts}")
